insert into capacite_classe (capcl_cla_ID,capcl_sousclasse,capcl_niveau,capcl_nom_capacite,capcl_description)
value 


(1,3,3,"Voie de la magie sauvage","De nombreux endroits dans le multivers regorgent de beauté, d\'émotions intenses et de magie effrénée. La Féerie, les plans supérieurs et d\'autres royaumes de puissances surnaturelles irradient de telles forces et peuvent profondément influencer les gens. En tant que personnes dotées de profonds sentiments, les barbares sont particulièrement sensibles à ces influences sauvages, et certains sont même transformés par la magie. Ces barbares imprégnés de magie empruntent la voie de la magie sauvage. Les barbares elfes, tieffelins, aasimars et génasis, désireux de manifester la magie d\'Outremonde de leurs ancêtres, suivent souvent cette voie."),
(1,3,3,"Sens de la magie","Capacité de la voie de la magie sauvage de niveau 3. Par une action, vous pouvez ouvrir votre conscience à la présence de magie concentrée. Jusqu\'à la fin de votre prochain tour, vous connaissez l\'emplacement de tout sort ou objet magique dans un rayon de 18 m autour de vous et qui n\'est pas caché par un abri total. Lorsque vous sentez un sort, vous reconnaissez à quelle école de magie il appartient. Vous pouvez utiliser cette capacité un nombre de fois égal à votre bonus de maîtrise, et vous récupérez toutes les utilisations dépensées lorsque vous terminez un repos long."),
(1,3,3,"Sursaut sauvage","Capacité de la voie de la magie sauvage de niveau 3. L\'énergie magique qui coule en vous jaillit parfois. Lorsque vous entrez en rage, lancez 1d8 sur la table de Magie sauvage pour déterminer l\'effet magique produit. Si l\'effet requiert un jet de sauvegarde, le DD est égal à 8 + votre bonus de maîtrise + votre modificateur de Constitution."),
(1,3,6,"Réserve de magie Capacité de la voie de la magie sauvage de niveau 6. Vous pouvez exploiter votre magie sauvage pour vous renforcer ou renforcer un compagnon. Par une action, vous pouvez toucher une créature (y compris vous-même) et lui conférer l\'un des avantages suivants de votre choix :-Durant 10 minutes, la créature peut lancer un d3 à chaque fois qu\'elle effectue un jet d\'attaque ou un jet de caractéristique, et ajouter le nombre obtenu au d20.-Lancez un d3. La créature regagne un emplacement de sort dépensé d\'un niveau égal ou inférieur au nombre obtenu (au choix de la créature). Une fois qu\'une créature reçoit cet avantage, elle ne peut plus en bénéficier avant de terminer un repos long. Vous pouvez effectuer cette action un nombre de fois égal à votre bonus de maîtrise, et vous récupérez toutes les utilisations dépensées lorsque vous terminez un repos long."),
(1,3,10,"Réaction instable Capacité de la voie de la magie sauvage de niveau 10. Lorsque vous êtes en danger pendant votre rage, votre magie intérieure peut se déchaîner. Immédiatement après avoir subi des dégâts ou échoué à un jet de sauvegarde pendant que vous êtes en rage, vous pouvez utiliser votre réaction pour lancer un dé sur la table de Magie sauvage et l\'effet obtenu se produit immédiatement. Cet effet remplace votre effet de Magie sauvage en cours."),
(1,3,14,"Sursaut contrôlé Capacité de la voie de la magie sauvage de niveau 14. Chaque fois que vous lancez un dé sur la table de Magie sauvage, vous pouvez lancer le dé deux fois et choisir lequel des deux effets se déclenche. Si vous lancez le même nombre sur les deux dés, vous pouvez ignorer le dé et choisir n\'importe quel effet sur la table."),
(2,4,3,"Collège du savoir","Les bardes du collège du savoir savent quelque chose sur tout, collectant des morceaux de connaissances à partir de sources aussi diverses que d\'anciens livres ou des contes de paysans. Qu\'ils chantent des ballades populaires dans les tavernes ou qu\'ils composent dans les cours royales, ces bardes utilisent leurs dons pour tenir le public en haleine. Lorsque les applaudissements s\'apaisent, les membres du public pourraient se questionner sur la véracité de ce qu\'ils tenaient pour vrai, de leur foi pour la religion du temple local jusqu\'à leur fidélité au roi. La loyauté de ces bardes réside dans la poursuite de la beauté et de la vérité, et non pas dans la fidélité à un monarque ou aux principes d\'une divinité. Un noble qui conserve un tel barde comme héraut ou conseiller sait que le barde préférera être honnête que politicien. Les membres du collège se réunissent dans des bibliothèques et parfois dans de vrais collèges, avec des salles de classe et des dortoirs, afin de partager leur savoir avec les autres. Ils se rencontrent également lors de festivals ou d\'affaires d\'état, où ils peuvent mettre à jour des corruptions, démêler des mensonges ou bien encore se moquer de certaines figures de l\'autorité."),
(2,4,3,"Maîtrises supplémentaires","Lorsque vous rejoignez le collège du savoir au niveau 3, vous gagnez la maîtrise des trois compétences de votre choix."),
(2,4,3,"Mots cinglants","Également au niveau 3, vous apprenez à utiliser votre esprit pour détourner l\'attention ou semer la confusion, ainsi qu\'à saper la confiance et la compétence des autres. Quand une créature que vous pouvez voir dans un rayon de 18 mètres autour de vous fait un jet d\'attaque, de caractéristique ou de dégâts, vous pouvez utiliser votre réaction pour dépenser une utilisation d\'Inspiration bardique et soustraire votre jet du résultat de la cible. Vous pouvez choisir d\'utiliser cette capacité après que la créature ait fait son jet, mais vous devez le faire avant que le MD ne dise si son jet est un succès ou un échec, ou avant que la créature inflige ses dégâts. La créature est immunisée si elle ne peut pas vous entendre ou si les charmes ne l\'affectent pas.");